# python /home/ojohnson/riptide/riptide/pipelines/pulsar_pipeline.py manager_config.yaml "/fred/oz203/data/PX094/J0523-2529/frequency_split/uwl_221109_114040_0/prepdata/1.9-3.0GHz/*.inf" /fred/oz203/data/PX094/J0523-2529/riptide_output
# Data format, 'presto' or 'sigproc'
data_format: presto

# Minimum and Maximum observing frequencies in MHz
fmin: 1856
fmax: 3008

# Number of time series searched in parallel
num_processes: 4

# Max value of DM x |sin(b)|. Sets an upper limit on DM trials as a function
# of observed sky coordinates. If left blank, no upper limit is applied.
dmsinb_max: 

# Hard DM trial limits, regardless of sky coordinates
# These fields can be left blank, in which case the associated limit is not applied.
dm_min: 0.0
dm_max: 100.0

# Minimum difference between consecutive DM trials
dm_step: 0.05

# Paths to configuration files for the searches. They must be placed in the
# same directory as this file.
search_configs:
    - config_UWL.yaml

##### Harmonic filtering
# See the flag_harmonics() function docstring for an explanation.
# 'enabled' can be True or False. False means that no removal of harmonic 
# candidates is attempted.
harmonic_filtering:
    enabled: True
    max_denominator: 30
    max_distance: 1.0
    snr_tol: 1.5

##### Candidate filtering
# The cap on candidate number is applied last, after all the other filters
# These fields can be left empty, in which case the corresponding filter is
# not applied
candidate_filters:
    dm_min: 1.0
    snr_min: 10
    max_number: 100